services:
  # React Frontend
  - type: web
    name: clicklink-frontend
    env: static
    rootDir: app
    buildCommand: npm run build
    publishDir: app/build
    
  # Node.js Backend
  - type: web
    name: clicklink-backend
    env: node
    rootDir: server
    buildCommand: cd ../app && npm install && npm run build
    startCommand: npm start
